# Generated by Django 5.0.4 on 2024-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformaJogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartao_imagem', models.ImageField(upload_to='jogos')),
                ('nome_jogo', models.CharField(max_length=120)),
                ('preco_jogo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Configuração Jogos Ajuste',
            },
        ),
    ]
