# Generated by Django 5.0.6 on 2024-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criaranotacao',
            name='id_anotacao',
        ),
        migrations.AddField(
            model_name='criaranotacao',
            name='id_card',
            field=models.IntegerField(blank=True, default=0, verbose_name='ID Anotação'),
        ),
    ]
